name: Daily Lucy Message

on:
  schedule:
    - cron: '0 7 * * *'  # 7:00 UTC = 9:00 Berlin
  workflow_dispatch: # optional manuelles Triggern

jobs:
  send-lucy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Lucy script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_NAME: ${{ secrets.DISCORD_CHANNEL_NAME }}
        run: npx tsx server/lucy-git-schedule.ts 
